benign:
  num_employees: 25
  start_date: "2025-01-01"
  end_date: "2025-01-10"
  
  # Optional - each number if per user per day.
  num_sign_ins_per_user_min: 1
  num_sign_ins_per_user_max: 5
  num_devices_per_user_min: 1
  num_devices_per_user_max: 4
  device_events_per_user_min: 1
  device_events_per_user_max: 10
  device_file_events_per_user_min: 0
  device_file_events_per_user_max: 5
  device_process_events_min: 0
  device_process_events_max: 10
  emails_per_user_min: 20
  emails_per_user_max: 30
  network_events_per_user_min: 20
  network_events_per_user_max: 50

attacks:
  reconnaissance:
    type: "phishing_for_information" # T1598: Phishing for Information
  initial_access:
    type: "malware" # T1105: Ingress Tool Transfer (Initial Access Malware)
    initial_access_malware:
      download_paths:
        - "Downloads"
        - "Documents"
        - "AppData\\Local\\Temp"
        - "AppData\\Roaming"
        - "Desktop"
      malware_files:
        - {name: "document", ext: ".doc"}
        - {name: "invoice", ext: ".pdf"}
        - {name: "report", ext: ".xls"}
        - {name: "update", ext: ".exe"}
        - {name: "installer", ext: ".msi"}
      download_time_minutes_min: 0
      download_time_minutes_max: 30
      c2_port_min: 8000
      c2_port_max: 9000
      file_creation_seconds_min: 1
      file_creation_seconds_max: 5
      process_creation_seconds_min: 6
      process_creation_seconds_max: 10
      device_event_seconds_min: 1
      device_event_seconds_max: 5
      c2_connection_seconds_min: 10
      c2_connection_seconds_max: 30
      timeline_c2_minutes_min: 5
      timeline_c2_minutes_max: 15
      file_number_digits: 4
      mitigation_recommendations:
        - "Isolate affected systems from the network"
        - "Reset passwords for affected accounts"
        - "Block identified malicious IP addresses and domains"
        - "Collect and preserve evidence for forensic analysis"
        - "Scan systems for additional malware"
        - "Review and update endpoint protection rules"
        - "Consider implementing application whitelisting"
  execution:
    type: "user_execution" # T1204: User Execution (Malicious File/Link)
  command_and_control:
    type: "cobalt_strike" # T1071: Application Layer Protocol (Cobalt Strike Beacon)
    simulation_params:
      jitter_percentage: 20  # Amount of random jitter to add to intervals for realistic variation
    network_patterns:
      domains:
        - "cdn.cloudflare.com"
        - "s3.amazonaws.com"
        - "cdn.akamai.com"
        - "static.fastly.net"
        - "assets.stackpath.com"
      prefixes:
        - "cdn"
        - "api"
        - "update"
        - "static"
        - "assets"
      uri_patterns:
        - "/jquery-3.3.1.min.js"
        - "/bootstrap.min.css"
        - "/api/v1/check"
        - "/updates/check.php"
      user_agents:
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
      c2_processes:
        - "svchost.exe"
        - "beacon.exe"
        - "csrss.exe"
        - "dllhost.exe"
        - "explorer.exe"
        - "chrome.exe"
        - "firefox.exe"
        - "msedge.exe"
        - "opera.exe"
      http_headers:
        Accept: ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"]
        Accept-Language: ["en-US,en;q=0.5"]
        Accept-Encoding: ["gzip, deflate, br"]
        Connection: ["keep-alive"]
        Cache-Control: ["max-age=0"]
        Upgrade-Insecure-Requests: ["1"]
        DNT: ["1"]
      protocols:
        - "TCP"
      c2_probability: 0.3
      beacons_per_victim_min: 3
      beacons_per_victim_max: 7
  lateral_movement:
    type: "remote_services" # T1021: Remote Services (RDP/SMB)
  impact:
    type: "ransomware" # T1486: Data Encrypted for Impact (Ransomware) 
    account_access_removal:
      type: "account_access_removal"
      recon_commands:
        - "net user /domain"
        - "Get-ADUser -Filter * -Properties *"
        - "net group /domain"
        - "Get-ADGroup -Filter *"
        - "Get-ADUser -Filter * -Properties MemberOf"
        - "net localgroup"
        - "Get-LocalUser"
        - "Get-LocalGroupMember -Group Administrators"
      admin_processes:
        - "powershell.exe"
        - "cmd.exe"
        - "net.exe"
        - "dsquery.exe"
        - "dsmod.exe"
      removal_commands:
        - "Disable-ADAccount -Identity {account}"
        - "net user {account} /active:no"
        - "Remove-ADGroupMember -Identity 'Domain Admins' -Members {account}"
        - "Remove-ADGroupMember -Identity 'Enterprise Admins' -Members {account}"
      cleanup_commands:
        - "wevtutil cl Security"
        - "wevtutil cl System"
        - "wevtutil cl Application"
        - "Remove-EventLog -LogName Security"
        - "Clear-EventLog -LogName System"
      recon_time_range: [0, 300]
      removal_time_range: [300, 600]
      cleanup_time_range: [600, 900]
      victim_selection_probability: 0.8
    ransomware:
      encryption_extensions:
        - ".encrypted"
        - ".locked"
        - ".crypted"
        - ".locked1"
        - ".crypt"
      target_directories:
        - "Documents"
        - "Desktop"
        - "Pictures"
        - "Videos"
        - "Downloads"
      ransom_note_names:
        - "README.txt"
        - "DECRYPT.html"
        - "HELP.html"
        - "HOW_TO_DECRYPT.txt"
      file_types_to_encrypt:
        - ".doc"
        - ".docx"
        - ".xls"
        - ".xlsx"
        - ".pdf"
        - ".jpg"
        - ".png"
        - ".txt"
      encryption_processes:
        - "ransomware.exe"
        - "cryptor.exe"
        - "winlock.exe"
        - "encryptor.exe"
      ransom_note_templates:
        - "Your files have been encrypted. To decrypt them, follow the instructions in this file."
        - "All your important files have been encrypted. Contact us to get the decryption key."
        - "Your files are now encrypted. Payment required for decryption key."
      cobalt_strike:
        team_server: "https://c2.example.com"
        profile: "default.profile"
        beacon_type: "http"
        sleep_time: 60
        jitter: 20
        processes:
          - "beacon.exe"
          - "csrss.exe"
          - "dllhost.exe"
          - "svchost.exe"
        ports: [80, 443, 8080]
        user_agents:
          - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          - "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)"
        uri_patterns:
          - "/jquery-3.3.1.min.js"
          - "/bootstrap.min.css"
          - "/api/v1/check"
          - "/updates/check.php"
        beacon_intervals: [60, 120, 180, 300]
      randomization:
        beacon_events_min: 5
        beacon_events_max: 15
        files_to_encrypt_min: 5
        files_to_encrypt_max: 15
        c2_beacon_events_min: 3
        c2_beacon_events_max: 7
        file_encrypt_interval_min: 1
        file_encrypt_interval_max: 3
        ransom_note_interval_min: 1
        ransom_note_interval_max: 2 