benign:
  num_employees: 25
  start_date: "2025-01-01"
  end_date: "2025-01-10"
  
  # Optional - each number if per user per day.
  num_sign_ins_per_user_min: 1
  num_sign_ins_per_user_max: 5
  num_devices_per_user_min: 1
  num_devices_per_user_max: 3
  device_events_per_user_min: 1
  device_events_per_user_max: 5
  device_file_events_per_user_min: 0
  device_file_events_per_user_max: 5
  device_process_events_min: 0
  device_process_events_max: 10
  emails_per_user_min: 20
  emails_per_user_max: 30
  network_events_per_user_min: 20
  network_events_per_user_max: 50
attacks:
  reconnaissance:
    type: "phishing_for_information" # options: "phishing_for_information, active_scan"
  initial_access:
    type: "valid_accounts" # options: "phishing, content_injection", "valid_accounts"
  execution:
    type: "user_execution" # options: "user_execution, command_scripting_interpreter"
  credential_access:
    type: "os_credential_dumping" # options: "password_spray, os_credential_dumping"
  lateral_movement:
    type: "remote_services" # options: "remote_services", "internal_spearphishing"
  collection:
    type: "email_collection" # options: "email_collection"
  exfiltration:
    type: "exfiltration_over_c2_channel"
    plausible_endpoints:
      - "https://malicious-c2.example.com/exfil"
      - "https://backup-c2.example.net/data"
  impact:
    type: "account_access_removal" # options: "account_access_removal"