benign:
  num_employees: 25
  start_date: "2025-01-01"
  end_date: "2025-01-10"
  
  # Optional - each number if per user per day.
  num_sign_ins_per_user_min: 1
  num_sign_ins_per_user_max: 5
  num_devices_per_user_min: 1
  num_devices_per_user_max: 4
  device_events_per_user_min: 1
  device_events_per_user_max: 5
  device_file_events_per_user_min: 0
  device_file_events_per_user_max: 5
  device_process_events_min: 0
  device_process_events_max: 10
  emails_per_user_min: 20
  emails_per_user_max: 30
  network_events_per_user_min: 20
  network_events_per_user_max: 50
attacks:
  reconnaissance:
    type: "phishing_for_information" # options: "phishing_for_information, active_scan"
  credential_access:
    type: "password_spray" # options: "password_spray, os_credential_dumping"
  initial_access:
    type: "valid_accounts" # options: "phishing, content_injection", "valid_accounts"
  collection:
    type: "email_collection" # options: "email_collection"
  lateral_movement:
    type: "internal_spearphishing" # options: "remote_services", "internal_spearphishing"
  exfiltration:
    type: "exfiltration_over_web" # options: "automated_exfiltration, exfiltration_over_web, exfiltration_over_c2_channel"
    plausible_endpoints:
      - "https://fileshare.example.com/upload"
      - "https://dropbox.com/api/upload"