benign:
  num_employees: 25
  start_date: "2025-01-01"
  end_date: "2025-01-10"
  
  # Optional - each number if per user per day.
  num_sign_ins_per_user_min: 1
  num_sign_ins_per_user_max: 5
  num_devices_per_user_min: 1
  num_devices_per_user_max: 3
  device_events_per_user_min: 1
  device_events_per_user_max: 5
  device_file_events_per_user_min: 0
  device_file_events_per_user_max: 5
  device_process_events_min: 0
  device_process_events_max: 10
  emails_per_user_min: 20
  emails_per_user_max: 30
  network_events_per_user_min: 20
  network_events_per_user_max: 50

attacks:
  reconnaissance:
    type: "active_scan"  # T1595: Active Scanning
  initial_access:
    type: "valid_accounts"  # T1210: Exploitation of Remote Services
  execution:
    type: "command_scripting_interpreter"  # T1059: Command and Scripting Interpreter (PowerShell/CMD)
  credential_access:
    type: "os_credential_dumping"  # T1003: OS Credential Dumping (NTDS/SAM)
  lateral_movement:
    type: "remote_services"  # T1021: Remote Services (RDP/SMB)
  persistence:
    type: "boot_or_logon_autostart_execution"  # T1547: Boot or Logon Autostart Execution (Registry Run Keys)
    common_registry_keys:
      - "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run"
      - "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"
  exfiltration:
    type: "exfiltration_over_c2_channel"  # T1041: Exfiltration Over C2 Channel 
    plausible_endpoints:
      - /api/telemetry
      - /upload
      - /gate.php
      - /data
      - /submit
      - /api/v1/upload
      - /api/collect
      - /api/receive
      - /exfil
      - /api.php 