from sqlalchemy import Column, Integer, String, Boolean, DateTime, BigInteger
from .base import Base

class AlertEvidence(Base):
    __tablename__ = 'AlertEvidence'
    
    Timestamp = Column(
        DateTime,
        comment="Date and time when the event was recorded"
    )
    AlertId = Column(
        String(255),
        primary_key=True,
        comment="Unique identifier for the alert"
    )
    Title = Column(
        String(255),
        comment="Title of the alert"
    )
    Categories = Column(
        String(255),
        comment="List of categories that the information belongs to, in JSON array format"
    )
    AttackTechniques = Column(
        String(255),
        comment="MITRE ATT&CK techniques associated with the activity that triggered the alert"
    )
    ServiceSource = Column(
        String(255),
        comment="Product or service that provided the alert information"
    )
    DetectionSource = Column(
        String(255),
        comment="Detection technology or sensor that identified the notable component or activity"
    )
    EntityType = Column(
        String(255),
        comment="Type of object, such as a file, a process, a device, or a user"
    )
    EvidenceRole = Column(
        String(255),
        comment="How the entity is involved in an alert, indicating whether it is impacted or is merely related"
    )
    EvidenceDirection = Column(
        String(255),
        comment="Indicates whether the entity is the source or the destination of a network connection"
    )
    FileName = Column(
        String(255),
        comment="Name of the file that the recorded action was applied to"
    )
    FolderPath = Column(
        String(255),
        comment="Folder containing the file that the recorded action was applied to"
    )
    SHA1 = Column(
        String(255),
        comment="SHA-1 of the file that the recorded action was applied to"
    )
    SHA256 = Column(
        String(255),
        comment="SHA-256 of the file that the recorded action was applied to. This field is usually not populated—use the SHA1 column when available."
    )
    FileSize = Column(
        BigInteger,
        comment="Size of the file in bytes"
    )
    ThreatFamily = Column(
        String(255),
        comment="Malware family that the suspicious or malicious file or process has been classified under"
    )
    RemoteIP = Column(
        String(255),
        comment="IP address that was being connected to"
    )
    RemoteUrl = Column(
        String(255),
        comment="URL or fully qualified domain name (FQDN) that was being connected to"
    )
    AccountName = Column(
        String(255),
        comment="User name of the account"
    )
    AccountDomain = Column(
        String(255),
        comment="Domain of the account"
    )
    AccountSid = Column(
        String(255),
        comment="Security Identifier (SID) of the account"
    )
    AccountObjectId = Column(
        String(255),
        comment="Unique identifier for the account in Microsoft Entra ID"
    )
    AccountUpn = Column(
        String(255),
        comment="User principal name (UPN) of the account"
    )
    DeviceId = Column(
        String(255),
        comment="Unique identifier for the device in the service"
    )
    DeviceName = Column(
        String(255),
        comment="Fully qualified domain name (FQDN) of the device"
    )
    LocalIP = Column(
        String(255),
        comment="IP address assigned to the local device used during communication"
    )
    NetworkMessageId = Column(
        String(255),
        comment="Unique identifier for the email, generated by Office 365"
    )
    EmailSubject = Column(
        String(255),
        comment="Subject of the email"
    )
    Application = Column(
        String(255),
        comment="Application that performed the recorded action"
    )
    ApplicationId = Column(
        Integer,
        comment="Unique identifier for the application"
    )
    OAuthApplicationId = Column(
        String(255),
        comment="Unique identifier of the third-party OAuth application"
    )
    ProcessCommandLine = Column(
        String(255),
        comment="Command line used to create the new process"
    )
    RegistryKey = Column(
        String(255),
        comment="Registry key that the recorded action was applied to"
    )
    RegistryValueName = Column(
        String(255),
        comment="Name of the registry value that the recorded action was applied to"
    )
    RegistryValueData = Column(
        String(255),
        comment="Data of the registry value that the recorded action was applied to"
    )
    AdditionalFields = Column(
        String(255),
        comment="Additional information about the entity or event"
    )
    Severity = Column(
        String(255),
        comment="Indicates the potential impact (high, medium, or low) of the threat indicator or breach activity identified by the alert"
    )
    CloudResource = Column(
        String(255),
        comment="Cloud resource name"
    )
    CloudPlatform = Column(
        String(255),
        comment="The cloud platform that the resource belongs to, can be Azure, Amazon Web Services, or Google Cloud Platform"
    )
    ResourceType = Column(
        String(255),
        comment="Type of cloud resource"
    )
    ResourceID = Column(
        String(255),
        comment="Unique identifier of the cloud resource accessed"
    )
    SubscriptionId = Column(
        String(255),
        comment="Unique identifier of the cloud service subscription"
    )
