from sqlalchemy import Column, Integer, BigInteger, String, DateTime  
from .base import Base  

class EmailAttachmentInfo(Base):  
    __tablename__ = 'EmailAttachmentInfo'  

    id = Column(
        Integer,  
        primary_key=True,  
        autoincrement=True  
    )

    Timestamp = Column(
        DateTime,  
        nullable=False,  
        comment="Date and time when the event was recorded"  
    )

    NetworkMessageId = Column(
        String(255),  
        comment="Unique identifier for the email, generated by Microsoft 365"  
    )

    SenderFromAddress = Column(
        String(255),  
        comment="Sender email address in the FROM header, which is visible to email recipients on their email clients"  
    )

    SenderDisplayName = Column(
        String(255),  
        comment="Name of the sender displayed in the address book, typically a combination of a given or first name, a middle initial, and a last name or surname"  
    )

    SenderObjectId = Column(
        String(255),  
        comment="Unique identifier for the sender's account in Microsoft Entra ID"  
    )

    RecipientEmailAddress = Column(
        String(255),  
        comment="Email address of the recipient, or email address of the recipient after distribution list expansion"  
    )

    RecipientObjectId = Column(
        String(255),  
        comment="Unique identifier for the email recipient in Microsoft Entra ID"  
    )

    FileName = Column(
        String(512),  
        comment="Name of the file that the recorded action was applied to"  
    )

    FileType = Column(
        String(50),  
        comment="File extension type"  
    )

    SHA256 = Column(
        String(64),  
        comment="SHA-256 of the file that the recorded action was applied to. This field is usually not populated — use the SHA1 column when available."  
    )

    FileSize = Column(
        BigInteger,  
        comment="Size of the file in bytes"  
    )

    ThreatTypes = Column(
        String(255),  
        comment="Verdict from the email filtering stack on whether the email contains malware, phishing, or other threats"  
    )

    ThreatNames = Column(
        String(255),  
        comment="Detection name for malware or other threats found"  
    )

    DetectionMethods = Column(
        String(255),  
        comment="Methods used to detect malware, phishing, or other threats found in the email"  
    )

    ReportId = Column(
        String(255),  
        comment="Event identifier based on a repeating counter. To identify unique events, this column must be used in conjunction with the DeviceName and Timestamp columns."  
    )
