from sqlalchemy import Column, Integer, BigInteger, String, DateTime  
from .base import Base  

class EmailUrlInfo(Base):  
    __tablename__ = 'EmailUrlInfo'  

    id = Column(
        Integer,  
        primary_key=True,  
        autoincrement=True  
    )

    Timestamp = Column(
        DateTime,  
        nullable=False,  
        comment="Date and time when the event was recorded"  
    )

    NetworkMessageId = Column(
        String(255),  
        comment="Unique identifier for the email, generated by Microsoft 365"  
    )

    Url = Column(
        String(2048),  
        comment="Full URL in the email subject, body, or attachment"  
    )

    UrlDomain = Column(
        String(255),  
        comment="Domain name or host name of the URL"  
    )

    UrlLocation = Column(
        String(100),  
        comment="Indicates which part of the email the URL is located"  
    )

    ReportId = Column(
        String(255),  
        comment="Event identifier based on a repeating counter. To identify unique events, this column must be used in conjunction with the DeviceName and Timestamp columns"  
    )
